---
title: "Portfolio Total Return Dashboard"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: cerulean
runtime: shiny
---

<style type="text/css">
.sidebar {  /* sidebar  */
   font-size: 12px;
</style>

<style>
#inputGroup > div {
  width: 100px !important;
  float: left !important;
  margin-right: 10px !important;
  vertical-align: top !important;
}
</style>

<style>
#heightGroup > div {
  height: 70px !important;
}
</style>

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyquant)
library(scales)
library(ggthemes)
```

Inputs {.sidebar data-width=260}
-----------------------------------------------------------------------
##### Choose ticker #1:
```{r}
div(div(textInput('ticker1', label ='Ticker #1:', 'VTI'),
dateInput("date1", label = "Purchase date:", '2016-01-19'), id = 'inputGroup'),
div(numericInput("price1", label = "Purchase price:", 95.31),
numericInput("shares1", label = "# of shares:", 120), id = 'inputGroup'), id = 'heightGroup')
```
</br>
 
##### Choose ticker #2:
```{r}
div(div(textInput('ticker2', label = 'Ticker #2', 'VNQ'),
dateInput("date2", label = "Purchase date:", '2015-10-20'), id = 'inputGroup'),
div(numericInput("price2", label = "Purchase price:", 80.82),
numericInput("shares2", label = "# of shares:", 40), id = 'inputGroup'), id = 'heightGroup')
```
</br>
 
##### Choose ticker #3:
```{r}
div(div(textInput('ticker3', label = 'Ticker #3', 'VGK'),
dateInput("date3", label = "Purchase date:", '2016-06-06'), id = 'inputGroup'),
div(numericInput("price3", label = "Purchase price:", 45.56),
numericInput("shares3", label = "# of shares:", 120), id = 'inputGroup'), id = 'heightGroup')
```
</br>
 
##### Choose ticker #4:
```{r}
div(div(textInput('ticker4', label = 'Ticker #4', 'EXC'),
dateInput("date4", label = "Purchase date:", '2016-01-19'), id = 'inputGroup'),
div(numericInput("price4", label = "Purchase price:", 27.40),
numericInput("shares4", label = "# of shares:", 175), id = 'inputGroup'), id = 'heightGroup')
```
</br>
 
##### Choose ticker #5:
```{r}
div(div(textInput('ticker5', label = 'Ticker #5', 'VNQ'),
dateInput("date5", label = "Purchase date:", '2016-02-24'), id = 'inputGroup'),
div(numericInput("price5", label = "Purchase price:", 75.52),
numericInput("shares5", label = "# of shares:", 30), id = 'inputGroup'), id = 'heightGroup')
```
</br>
 
##### Choose ticker #6:
```{r}
div(div(textInput('ticker6', label = 'Ticker #6', ''),
dateInput("date6", label = "Purchase date:", ''), id = 'inputGroup'),
div(numericInput("price6", label = "Purchase price:", NA),
numericInput("shares6", label = "# of shares:", NA), id = 'inputGroup'), id = 'heightGroup')
```
</br>
 
##### Choose ticker #7:
```{r}
div(div(textInput('ticker7', label = 'Ticker #7', ''),
dateInput("date7", label = "Purchase date:", ''), id = 'inputGroup'),
div(numericInput("price7", label = "Purchase price:", NA),
numericInput("shares7", label = "# of shares:", NA), id = 'inputGroup'), id = 'heightGroup')
```
</br>
 
##### Choose ticker #8:
```{r}
div(div(textInput('ticker8', label = 'Ticker #8', ''),
dateInput("date8", label = "Purchase date:", ''), id = 'inputGroup'),
div(numericInput("price8", label = "Purchase price:", NA),
numericInput("shares8", label = "# of shares:", NA), id = 'inputGroup'), id = 'heightGroup')
```
</br>
 
##### Choose ticker #9:
```{r}
div(div(textInput('ticker9', label = 'Ticker #9', ''),
dateInput("date9", label = "Purchase date:", ''), id = 'inputGroup'),
div(numericInput("price9", label = "Purchase price:", NA),
numericInput("shares9", label = "# of shares:", NA), id = 'inputGroup'), id = 'heightGroup')
```

Column
-----------------------------------------------------------------------

### Returns (as of `r Sys.Date()-1`)

```{r echo = FALSE}
renderTable({
    
  input_list <- reactiveValuesToList(input)
    
  input_tickers <- input_list[grep('ticker', names(input_list))]
  input_tickers <- input_tickers[input_tickers != '']
  input_tickers <- input_tickers[order(names(input_tickers))]
  input_tickers <- unlist(input_tickers)
    
  input_dates <- input_list[grep('date', names(input_list))]
  input_dates <- input_dates[input_dates != '']
  input_dates <- input_dates[order(names(input_dates))]
  input_dates <- unlist(input_dates)

  input_shares <- input_list[grep('shares', names(input_list))]
  input_shares <- input_shares[!is.na(input_shares)]
  input_shares <- input_shares[order(names(input_shares))]
  input_shares <- unlist(input_shares)
    
  input_prices <- input_list[grep('price', names(input_list))]
  input_prices <- input_prices[!is.na(input_prices)]
  input_prices <- input_prices[order(names(input_prices))]
  input_prices <- unlist(input_prices)
    
  #ensure all vectors are the same length by trimming to the length of the ticker list
  input_dates <- input_dates[1:length(input_tickers)]
  input_shares <- input_shares[1:length(input_tickers)]
  input_prices <- input_prices[1:length(input_tickers)]
    
  percent_func <- function(x, digits = 1, format = 'f') {
    paste0(formatC(100 * x, format = format, digits = digits), "%")
  }
    
  return_func <- function(ticker, shares, price, pdate){
    tmp <- tq_get(ticker, get = "stock.prices", from = pdate) %>%
      filter(date == min(date) | date == max(date)) %>%
      arrange(date) %>%
      summarise(ticker = ticker, shares = shares,
                current_price = close[2],
                purchase_price = ifelse(price == 0, close[1], price),
                initial_value = shares*purchase_price,
                current_value = shares*close[2],
                initial_value_adj = shares*(adjusted[1] - (close[1] - purchase_price)),
                total_return = current_value - initial_value_adj,
                price_return = current_value - initial_value,
                div_return = total_return - price_return,
                delta_days = as.numeric(max(date) - min(date)))
  }
    
  return_dat <- pmap_df(list(input_tickers, input_shares, input_prices, input_dates), return_func)
    
  return_dat_disp <- return_dat %>%
    group_by(ticker) %>%
    summarise(total_shares = sum(shares),
              current_price = min(current_price),
              current_value = sum(current_value),
              initial_value = sum(initial_value),
              initial_value_adj = sum(initial_value_adj),
              total_return = sum(total_return), 
              price_return = sum(price_return),
              div_return = sum(div_return),
              delta_days = sum(delta_days*shares)/sum(shares)) %>%
    ungroup() %>%
    mutate(weight = percent_func(current_value/sum(current_value)),
           `purchase price` = dollar(initial_value/total_shares),
           `current price` = dollar(current_price),
           `current value` = dollar(round(current_value, digits = 0)),
           `total return` = dollar(round(total_return, digits = 0)),
           `% total return` = percent_func(total_return/initial_value),
           `% price return` = percent_func(price_return/initial_value),
           `% div return` = percent_func(div_return/initial_value),
           `% div AR` = percent_func((1 + (div_return/initial_value))^(365/delta_days) - 1),
           `% total AR` = percent_func((1 + (total_return/initial_value))^(365/delta_days) - 1)) %>%
    select(ticker, weight, `purchase price`, `current price`, `current value`, `total return`,
           `% total return`, `% price return`, `% div return`, `% total AR`, `% div AR`)

    
  sum_return_dat <- return_dat %>%
    summarise(sum_current_value = sum(current_value),
            sum_total_return = sum(total_return),
            sum_pct_total_return = sum(total_return)/sum(initial_value),
            sum_pct_price_return = sum(price_return)/sum(initial_value),
            sum_pct_div_return = sum(div_return)/sum(initial_value),
            sum_pct_div_return_ann = (1 + sum(div_return)/sum(initial_value))^(365/max(delta_days)) - 1,
            sum_pct_total_return_ann = (1 + sum(total_return)/sum(initial_value))^(365/max(delta_days)) - 1) %>%
    mutate(ticker = 'TOTAL', weight = '100%',
            `purchase price` = '',
            `current price` = '',
            `current value` = dollar(round(sum_current_value, digits = 0)), 
            `total return` = dollar(round(sum_total_return, digits = 0)),
            `% total return` = percent_func(sum_pct_total_return),
            `% price return` = percent_func(sum_pct_price_return),
            `% div return` = percent_func(sum_pct_div_return),
            `% div AR` = percent_func(sum_pct_div_return_ann),
            `% total AR` = percent_func(sum_pct_total_return_ann)) %>%
    select(ticker, weight, `purchase price`, `current price`, `current value`, `total return`,
            `% total return`, `% price return`, `% div return`, `% total AR`, `% div AR`)
    
  display_tbl <- rbind(return_dat_disp, sum_return_dat)

}, align = 'c', striped = TRUE, hover = TRUE)
```

###
```{r}
div(style="display: inline-block;vertical-align:top; width: 100px; height: 20px",paste('Benchmark:'))
div(style="display: inline-block;vertical-align:top; width: 100px; height: 20px",selectInput('benchmark_id', NULL, choices =  c('SPY', 'SHY', 'IWM', 'BND', 'VT'), selectize = FALSE, size = 1))
```

###
```{r echo=FALSE}
renderPlot({

  input_list <- reactiveValuesToList(input)

  input_tickers <- input_list[grep('ticker', names(input_list))]
  input_tickers <- input_tickers[input_tickers != '']
  input_tickers <- input_tickers[order(names(input_tickers))]
  input_tickers <- unlist(input_tickers)

  input_dates <- input_list[grep('date', names(input_list))]
  input_dates <- input_dates[input_dates != '']
  input_dates <- input_dates[order(names(input_dates))]
  input_dates <- unlist(input_dates)

  input_shares <- input_list[grep('shares', names(input_list))]
  input_shares <- input_shares[!is.na(input_shares)]
  input_shares <- input_shares[order(names(input_shares))]
  input_shares <- unlist(input_shares)

  input_prices <- input_list[grep('price', names(input_list))]
  input_prices <- input_prices[!is.na(input_prices)]
  input_prices <- input_prices[order(names(input_prices))]
  input_prices <- unlist(input_prices)

  #ensure all vectors are the same length by trimming to the length of the ticker list
  input_dates <- input_dates[1:length(input_tickers)]
  input_shares <- input_shares[1:length(input_tickers)]
  input_prices <- input_prices[1:length(input_tickers)]

  plot_return_func <- function(ticker, shares, price, pdate){
    tmp <- tq_get(ticker, get = "stock.prices", from = pdate) %>%
      mutate(ticker = ticker, shares = shares, purchase_price = price, flag = 'portfolio') %>%
      arrange(date) %>%
      mutate(purchase_price = ifelse(purchase_price == 0, close[1], purchase_price),
             initial_value = shares*purchase_price,
             initial_adjustment = close[1] - adjusted[1],
             adjustment = initial_adjustment - (close - adjusted),
             total_return = shares*(close + adjustment) - initial_value,
             pct_total_return = total_return/initial_value)
  }
    
  plot_dat <- pmap_df(list(input_tickers, input_shares, input_prices, input_dates), plot_return_func)
    
  initial_values <- plot_dat %>%
    group_by(date) %>%
    summarise(initial_value = sum(initial_value))

  bench_shares <- tq_get(input$benchmark_id, get = "stock.prices", from = min(input_dates)) %>%
    inner_join(initial_values, by = 'date') %>%
    filter(date %in% as.Date(input_dates, origin = '1970-01-01')) %>%
    group_by(date) %>%
    mutate(total_shares = initial_value/close,
           delta_shares = ifelse(is.na(total_shares - lag(total_shares)), total_shares,
                                 total_shares - lag(total_shares))) %>%
  pull(delta_shares)

  bench_return_func <- function(ticker, shares, pdate){
    tmp <- tq_get(ticker, get = "stock.prices", from = pdate) %>%
      arrange(date) %>%
      mutate(ticker = ticker, shares = shares, flag = 'benchmark',
             purchase_price = close[1],
             initial_value = (shares*purchase_price),
             initial_adjustment = close[1] - adjusted[1],
             adjustment = initial_adjustment - (close - adjusted),
             total_return = shares*(close + adjustment) - initial_value,
             pct_total_return = total_return/initial_value) %>%
      ungroup()
  }

  input_dates <- unique(input_dates)
  
  bench_dat <- pmap_df(list(rep(input$benchmark_id, length(input_dates)), bench_shares, input_dates),
                     bench_return_func)

  plot_dat <- bind_rows(plot_dat, bench_dat)

  plot_dat %>%
    group_by(flag, date) %>%
    summarize(total_return = sum(total_return),
              initial_value = sum(initial_value),
              pct_total_return = total_return/initial_value) %>%
    ggplot(aes(x = date, y = pct_total_return, color = flag)) + geom_line() +
    ggtitle('Portfolio total return vs benchmark') +
    theme_tufte(base_family = 'Tahoma') +
    theme(panel.grid.major = element_line(size = 0.1, color = "grey"),
          axis.text.y = element_text(size = 10),
          axis.text.x = element_text(size = 10),
          axis.title.x = element_blank(), axis.title.y=element_blank(),
          plot.title = element_text(hjust = 0.5, face = 'bold', size = 18),
          legend.position = 'left', legend.title = element_blank(),
          legend.text = element_text(size = 12)) +
    scale_y_continuous(labels = scales::percent, position = 'right')
    
})
```

